initial_configuration:
  joint_state:
    # Above table:
    - { name: torso_lift_joint,       position: 0.0 }
    - { name: r_shoulder_pan_joint,   position: -1.68651 }
    - { name: r_shoulder_lift_joint,  position: -0.184315 }
    - { name: r_upper_arm_roll_joint, position: -1.67611 }
    - { name: r_elbow_flex_joint,     position: -1.66215 } # limit: -0.2 }
    - { name: r_forearm_roll_joint,   position: 0.285096 }
    - { name: r_wrist_flex_joint,     position: -0.658798 } # limit: -0.2 }
    - { name: r_wrist_roll_joint,     position: 1.41563 }

goal:
  x: 0.7
  y: 0.0
  z: 0.9
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  plan_budget: 300.0
  sim_budget: 900.0
  total_budget: 300.0
  save: true
  cc_2d: true
  cc_3d: false

robot:
  x: 0.0
  y: 0.0
  z: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 1.0
  semi_minor: 0.05
  robot_obj_mass: 0.5
  speed: 1.0
  pushes: 4
  plan_push_time: 10.0
  grasp_tries: 10
  grasp_lift: 0.075
  grasp_clip: 5
  interpolate: false

whca:
  window: 4
  goal_thresh: 0.02
  res: 0.05
  grid: 4
  cost_mult: 1000
  planning_time: 300.0

objects:
  min_size: 0.03
  x_size: 0.08
  y_size: 0.08
  z_size: 0.2
  num_immov: 5
  num_mov: 5
  ycb: false
